### PR TITLE
Create detect-unexpected-bugs.md

### PR DESCRIPTION
**Pull request by moodmosaic**
Hope you like the idea!

I thought it's better to add to your notes instead of creating mine (and maintaining a fork). Keep up the good work!

### CODE REVIEW

**Comment by moodmosaic** [comment]
Markdown preview [here](https://github.com/LNow/clarity-notes/blob/715d1c142cc3b2bcee4ab8613d4aa426f7acda55/ideas/detect-unexpected-bugs.md).

**Comment by LNow** [comment]
Hey @moodmosaic!
I must admit that it is the first time I see this testing approach and I'm not sure if I fully understand how it works and what benefits it brings.

Can you please show me how would you use it to test following contract?

```clarity
(define-constant ERR_NOT_AUTHORIZED (err u200))

(define-map ValuesMap
    uint ;; block-height
    uint ;; value
)

(define-data-var isInitialized bool false)

(define-public (initialize)
    (begin
        (asserts! (not (var-get isInitialized)) ERR_NOT_AUTHORIZED)
        (ok (var-set isInitialized true))
    )
)

(define-read-only (get-value (bh uint))
    (map-get? ValuesMap bh)
)

(define-public (set-values (values (list 100 uint)))
    (begin
        (asserts! (var-get isInitialized) ERR_NOT_AUTHORIZED)
        (fold set-value values block-height)
        (ok true)
    )
)

(define-private (set-value (value uint) (bh uint))
    (begin
        (map-set ValuesMap bh (+ (default-to u0 (get-value bh)) value))
        (+ bh u1)
    )
)
```
What I'm interested the most is verification if `set-values` works correctly if I call it multiple times in a row at the same block, and when I call multiple times at different block height.
Is it possible to cover such cases with this approach?

**Comment by moodmosaic** [comment]
Sure! But first, let me fully understand:

>if I call it multiple times in a row at the same block, and when I call multiple times at different block height

You mean one transaction per block *vs* many transactions in one block, right? (Which is something you can already test with clarinet, just manually.)

**Comment by LNow** [comment]
There are few scenarios:
1) one transaction (just single `set-values` call in a single block) 
2) multiple transactions in a single block (multiple calls of `set-values`, all in the same block)
3) multiple transactions but spread across multiple blocks (1 TX per block)
4) multiple transactions spread across multiple blocks (multiple TX per block)

I know how to write tests to cover all of these scenarios (I did this for CityCoins) - just want to see whether with your approach I could achieve the same result, if that's possible how it would look like and if I could do it with less code than with my usual approach.

**Comment by moodmosaic** [comment]
If you type here how you'd normally test this it would help me get back to you quicker (I'm out and about this week) as I won't have to deal with writing the clarinet stuff and I'll just build the commands. (But if you can't, that's fine.)

**Comment by LNow** [comment]
Here is example how I would do it: https://github.com/LNow/testing-example
It doesn't cover 4th scenario but I it would look just like other tests but with different data.

**Comment by moodmosaic** [comment]
I *very much* like your testing library. I think you should open an issue in clarinet to include your library as the default. I know it's easier said than done as there are existing tutorials out there and they'd have to be updated.

Let me see if I can quickly digest your testing library, then I can probably adapt the commands there, otherwise I'll just do the it using vanilla clarinet tests. (Again, I'm out and about this week so please stay tuned.)

Thanks for sharing https://github.com/LNow/testing-example.

**Comment by moodmosaic** [comment]
I just did a REPL session to get closer with the idea behind the example contract you provided:

```clar
>> (contract-call? .example initialize)
(ok true)

>> (contract-call? .example set-values (list u10 u20 u30))
(ok true)

>> (contract-call? .example get-value u0)
(some u10)
>> (contract-call? .example get-value u1)
(some u20)
>> (contract-call? .example get-value u2)
(some u30)
>> (contract-call? .example get-value u3)
none

>> (contract-call? .example set-values (list u1 u2 u3 u40))
(ok true)

>> (contract-call? .example get-value u0)
(some u11)
>> (contract-call? .example get-value u1)
(some u22)
>> (contract-call? .example get-value u2)
(some u33)
>> (contract-call? .example get-value u3)
(some u40)
```

Ok, I kind of see how it's working. However, I can't seem to follow the `expectUint` results of this test:

```ts
it("succeeds and store values when called once per block over multiple blocks", () => {
  const txSender = accounts.get("wallet_5")!;
  const values = [1, 2, 3];
  const setValuesTx = example.setValues(values, txSender);

  // act
  const receipts = [
    chain.mineBlock([setValuesTx]).receipts[0],
    chain.mineBlock([setValuesTx]).receipts[0],
    chain.mineBlock([setValuesTx]).receipts[0],
  ];

  // assert
  for (let receipt of receipts) {
    receipt.result.expectOk().expectBool(true);
  }

  example.getValue(2).expectSome().expectUint(1); // 1
  example.getValue(3).expectSome().expectUint(3); // 2 + 1
  example.getValue(4).expectSome().expectUint(6); // 3 + 2 + 1
  example.getValue(5).expectSome().expectUint(5); // 3 + 2
  example.getValue(6).expectSome().expectUint(3); // 3
});
```

**Comment by moodmosaic** [comment]
Oh, I guess block-height is already `2` by the time it enters that test.

**Comment by LNow** [comment]
`set-values` accepts lists of `uint` that we can describe as `(list n1 n2 n3 n4 .... nX)` and these values are stored in a map in a following manner:
 - n1 is stored under key `block-height`
 - n2 is stored under `block-height + 1`
 - n3 is stored under `block-height + 2`
 - ...
 - nX is stored under `block-height + X + 1`

If something is already stored under a specific key, value we want to store is added to what is already stored.

That being said following code mines 3 separate blocks with exactly the same `set-values` call with values `1, 2 and 3`
```ts
chain.mineBlock([setValuesTx]).receipts[0],
chain.mineBlock([setValuesTx]).receipts[0],
chain.mineBlock([setValuesTx]).receipts[0],
```

- 1st `set-value` saves:
  - 1 under key 2 (because it was mined at block 2)
  - 2 under key 3
  - 3 under key 4

- 2nd `set-value` saves:
  - 1 under key 3 (because it was mined at block 3)
  - 2 under key 4
  - 3 under key 5

- 3nd `set-value` saves:
  - 1 under key 4 (because it was mined at block 4)
  - 2 under key 5
  - 3 under key 6

here is how it looks like after each block:

|                     | key: 2 | key: 3 | key: 4 | key: 5 | key: 6 |
|---------------------|--------|--------|--------|--------|--------|
| before any tx       | none   | none   | none   | none   | none   |
| after 1st `set-value` | 1      | 2      | 3      | none   | none   |
| after 2nd `set-value` | 1      | 3      | 5      | 3      | none   |
| after 3rd `set-value` | 1      | 3      | 6      | 5      | 3      |

**Comment by moodmosaic** [comment]
OK, I see. Then, in addition to the existing ([example-based](https://fsharpforfunandprofit.com/posts/property-based-testing-1/#combining-property-based-tests-with-example-based-tests)) tests you can add some property-based ones. I've [added one](https://github.com/LNow/testing-example/pull/1) for you which can cover the [4th scenario](https://github.com/LNow/clarity-notes/pull/2#issuecomment-1109013377).

Model-based testing is one step beyond property-based testing; it arbitrarily executes actions (commands) on the contract. This will be my next PR.

**Comment by moodmosaic** [comment]
Here's [a good article](https://medium.com/criteo-engineering/detecting-the-unexpected-in-web-ui-fuzzing-1f3822c8a3a5) as a companion to the [CI tests](https://github.com/LNow/testing-example/pull/2) PR I just added.

I tend to call them *CI tests* because we usually prefer to run them outside the red/green/refactor cycle.

**Comment by moodmosaic** [comment]
>Can you please show me how would you use it to test following contract?

I did via https://github.com/LNow/testing-example/pull/1 and https://github.com/LNow/testing-example/pull/2. If you're still interested in adding this technique in clarity-notes, before merging this perhaps we should add those PRs to the notes too.

In any case, the outcome has been great as I'm now using your small library as part of my clarinet tests 🍻

**Review by LNow — CHANGES_REQUESTED** [review]
@moodmosaic can you add links to https://github.com/LNow/testing-example/blob/5f7eedf3edd9ee174650b59b4c181ddfdf713e41/tests/example.test-ci.ts and https://github.com/LNow/testing-example/blob/5f7eedf3edd9ee174650b59b4c181ddfdf713e41/tests/ci/example.commands.ts with few words of comments what they contains (especially the 2nd one)?

**Comment by moodmosaic** [comment]
Sure. I'll do that soon.

**Review by LNow — APPROVED** [review]
Thank you @moodmosaic !!!

**Pull request merged**
